from data_types_formatted_output.classwork.expression1 import calculate_expression1, ExpressionValues
from data_types_formatted_output.classwork.expression2 import calculate_expression2
from data_types_formatted_output.classwork.remainder import calculate_remainder
from data_types_formatted_output.classwork.speed_in_ms import get_speed_in_ms
from data_types_formatted_output.homework.time_in_seconds import translate_from_seconds
from data_types_formatted_output.homework.first_and_last_digits import swap_first_and_last_digits
from data_types_formatted_output.homework.glueing_numbers import glue_numbers_without_last_digits
from data_types_formatted_output.homework.lag_time import find_lag_time, TimeValues
from data_types_formatted_output.homework.packages_for_bottles import find_number_of_packages
from data_types_formatted_output.homework.probability_2_white_balls import get_probability_of_two_white_balls
from data_types_formatted_output.homework.result_of_calculations import get_result_of_calculations, ValuesForCalculation
from data_types_formatted_output.homework.sin_cos_tg_of_angle import calculate_sin_cos_tg_of_angle, DegreeValues
