from while_loop.classwork.squares_of_natural_numbers import get_squares_of_natural_numbers
from while_loop.classwork.increasing_contribution import increasing_contribution
from while_loop.classwork.n_numbers import create_n_numbers
from while_loop.homework.define_fibonacci_number import define_fibonacci_number
from while_loop.homework.sum_of_local_min import sum_of_local_min
from while_loop.homework.generating_series import generating_series
from while_loop.homework.solving_equation import solving_equation
