from lambda_function.area_of_circle import get_area_of_circle
from lambda_function.areas_of_circles import get_areas_of_circles
from lambda_function.is_number import is_string_number
from lambda_function.contain_letter_and_digit import contain_letter_and_digit
from lambda_function.nth_fibonacci_number import get_nth_fibonacci_number
